### ISSUE TITLE
accent error 

### ISSUE THREAD

**Issue by mariomatar** [jhonnymertz/java-wkhtmltopdf-wrapper#13]
Hi, 

I use your lib like this : 

    try {
            String html = menuDisplay(orderNumber, documentType);

            Pdf pdf = new Pdf();
            pdf.addPage(html, PageType.htmlAsString);
            pdf.addParam(new Param("--no-footer-line"));

            return pdf.getPDF();
        } catch (Exception e) {
            throw new ServerException("Error pdf convertion", e);
        }

And the output result does not have accent, example 

MaÃ®tre d'hÃ´tel (
â‚¬ 268,52 HT 

Idea ?

Thanks for your lib and your respons

**Comment by jhonnymertz** [comment]
It seems not a problem with the wrapper itself.

Try to specify the character encoding for the HTML document:
`<head><meta charset="UTF-8"></head>`

Of course, it presupposes your page is served as utf-8; otherwise, you can change the charset to another one.

If still won't work, you can try to configure the input encoding of wkhtmltopdf as well by adding another parameter to the command line:
`--encoding UTF-8`

Something like this:
`pdf.addParam(new Param("--encoding", "UTF-8"));`

**Comment by mariomatar** [comment]
it works !
