### ISSUE TITLE
Why does your code in the class Page delete source files in line 41?

### ISSUE THREAD

**Issue by JakobEichler** [jhonnymertz/java-wkhtmltopdf-wrapper#167]
Let's asume someone who uses your api reconfigures an existing Page object to use a html input string instead of some input file, but for convenience does not remove the source file path that was used before.... In this case his source file will be deleted in the getCommandAsList method without warning? So the method does something (like deleting a file) that an API user would never expect!?

` 
public List<String> getCommandAsList(Pdf pdf) throws IOException {
        List<String> commands = new ArrayList();
        if (StringUtils.isNotBlank(this.objectIdentifier)) {
            commands.add(this.objectIdentifier);
        }

        if (this.getType().equals(SourceType.htmlAsString)) {
            if (this.getFilePath() != null) {
                Files.deleteIfExists(Paths.get(this.getFilePath()));
            }`

**Comment by jhonnymertz** [comment]
Hi @JakobEichler, this is only applied when the page to be rendered is given as a String. This library is a wrapper for wkhtmltopdf which is called as command internally, and to avoid a huge command line the library writes the String into a temporary file and gives the file path to the command, instead of the whole String. The line you saw refers to the deletion of the temporary file created to hold that string. We do this to avoid consuming disk space with temporary files.

This is clearly indicated in the source code as comment: https://github.com/jhonnymertz/java-wkhtmltopdf-wrapper/blob/13c44f0743ef1e8b17b7e1716eb4cfd482e79f12/src/main/java/com/github/jhonnymertz/wkhtmltopdf/wrapper/objects/Page.java#L53
