### ISSUE TITLE
How to invoke a remote host wkhtmltopdf service 

### ISSUE THREAD

**Issue by danmaidesenling** [jhonnymertz/java-wkhtmltopdf-wrapper#55]

**Comment by jhonnymertz** [comment]
Hi @danmaidesenling, I need more information on what you mean by "invoking a remote host wkhtmltopdf service". This library is intended to be a Java wrapper for wkhtmltopdf program. So, you can call wkhtmltopdf programmatically instead of via command-line. Not sure if invoking a remote host is under the scope of this library.

So, please, provide an example of what do you need or what is the problem you are trying to solve, so I can try to help.
