### ISSUE TITLE
Korean characters are not supported

### ISSUE THREAD

**Issue by javacodecrusader** [jhonnymertz/java-wkhtmltopdf-wrapper#56]
**Describe the bug**
Korean Characters are not displaying as expected but rendered as a boxes.

**To Reproduce**
i am giving html as an input and when i open generated PDF then it does not show me Korean letter but a boxes.

**Expected behavior**
Korean character should be displayed
**Environment (please complete the following information):**
 - java-wkhtmltopdf-wrapper version:1. 1.10-RELEASE
 - wkhtmltopdf version:  0.0.1-SNAPSHOT

**Additional context**
My Html is : <html><head><meta charset=\"UTF-16\"></head><h1> 유니코드에 대해   Test 유니코드 </p></html>

**Comment by javacodecrusader** [comment]
I tried with UTF-8 and UTF-16 but nothing worked for me. 
I have added below line as well in my test program 
pdf.addParam(new Param("--encoding", "UTF-8"));
but o luck.


below is snippet of my test program  :
Pdf pdf = new Pdf();
		pdf.addPageFromString("<html><head><meta charset=\\\"UTF-8\\\"></head><h1> 유니코드에 대해   Test 유니코드 </p></html>/html>");
		pdf.addParam(new Param("--encoding", "UTF-8"));

**Comment by jhonnymertz** [comment]
Hi @javacodecrusader, I've tested the code below:

```
Pdf pdf = new Pdf();
pdf.addPageFromString("<meta charset=\"UTF-8\"> 유니코드에 대해 Test 유니코드");
pdf.saveAs("output.pdf");
```

And the file is ok, as you can see here: 

![Screenshot from 2019-04-07 15-12-20](https://user-images.githubusercontent.com/4013905/55687811-98a4d480-5947-11e9-9645-c31375724f5b.png)
Check the file: [output.pdf](https://github.com/jhonnymertz/java-wkhtmltopdf-wrapper/files/3051906/output.pdf)

I've seen some reports around the internet about black boxes instead of the international characters, but it seems your server lacks language-specific _fonts_ that are used to render the pdf. This is a typical situation in case of Windows Server. Here we have a similar thread https://stackoverflow.com/questions/25833954/wkhtmltopdf-and-chinese-characters. So, please, check whether you have all the international fonts installed.

**Comment by javacodecrusader** [comment]
Thanks for quick reply. 
i am running my program on window 10 and still facing issue.

**Comment by javacodecrusader** [comment]
Thanks @jhonnymertz ; 
You are correct, on my server font was missing. 
As per my understanding, code reads fronts from /jre/lib/fonts/ and also looks in system font folder and it picks it. Apart from it JDK reads file fontconfig.properties  from /jre/lib/ and observe which font to use.

so i made these changes and it start working
